[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = ""
authors = ["TurtleOld <shurpo.alexander@gmail.com>"]
packages = [
    { include = "task_manager"},
    { include = "users"},
]

[tool.poetry.dependencies]
python = "^3.9"
gunicorn = "^20.1.0"
Django = "^4.0.4"
python-dotenv = "^0.20.0"
dj-database-url = "^0.5.0"
psycopg2-binary = "^2.9.3"
whitenoise = "^6.1"
django-filter = "^21.1"
django-bootstrap4 = "^22.1"
rollbar = "^0.16.2"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
PyYAML = "^6.0"
Faker = "^13.7.0"
coverage = "^6.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
